version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flutterpr1-prapi:
    build: ./flutterpr1-prapi
    ports:
      - 7777:7777
    environment:
      # DATABASE_URL: postgres://postgres:password@db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      PORT: 7778
    depends_on:
      - postgres
volumes:
  postgres_data: